spring:
  application:
    name: issue-management-system
  datasource:
    url: ${DB_URL:your_url}
    username: ${DB_USERNAME:your_username}
    password: ${DB_PASSWORD:your_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

api:
  prefix: "/api/v1"

open:
  api:
    title: "JUST FOR FUN"
    description: "Lam cho vui thoi"
    version: "v0.0.1"
    serverUrl: "http://localhost:8080/"
    serverName: "Da bao lam cho vui roi ma"

minio:
  url: ${MINIO_URL:your_minio_url}
  access-key: ${MINIO_ACCESS_KEY:your_minio_access_key}
  secret-key: ${MINIO_SECRET_KEY:your_minio_secret_key}
  bucket: ${MINIO_BUCKET:your_minio_bucket}
  expiry: ${MINIO_EXPIRY:3600}

app:
  init-data: false